### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by rolandsmeenk** [HolAutisme/PopBalloons#1]
I just found this public repo after searching for the _HoloLens Shader Pack_ that I am selling on the AssetStore. According to the Unity Asset Store regulations you are not allowed to do that.
I suggest to make your repository private or remove the _HoloLens Shader Pack_ content from it.

kind regards,

Roland Smeenk

**Comment by HolAutisme** [comment]
Hi Roland,

Thank's for bringing this up to us, the shader pack was uploaded by mistake.  The entire folder has been removed from the project. I also cleared the git history so it doesn't appear anywhere anymore.

I'll wait a few days before closing the issue in order to let you check if everything is ok.

Sorry for the inconvenience and thank's again,

Alexis for the Hol'Autisme team.

**Comment by rolandsmeenk** [comment]
Thanks for the quick response.
